// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","layout":false,"id":"1"},"2":{"path":"/","redirect":"/student/equipments","parentId":"ant-design-pro-layout","id":"2"},"3":{"path":"/student","name":"Sinh viên","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/student/equipments","name":"Mượn thiết bị","parentId":"3","id":"4"},"5":{"path":"/student/history","name":"Lịch sử mượn","parentId":"3","id":"5"},"6":{"path":"/admin","name":"Admin","access":"canAdmin","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/admin/dashboard","name":"Thống kê","parentId":"6","id":"7"},"8":{"path":"/admin/equipments","name":"Quản lý thiết bị","parentId":"6","id":"8"},"9":{"path":"/admin/requests","name":"Duyệt yêu cầu","parentId":"6","id":"9"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__student__Equipments__index" */'@/pages/student/Equipments/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__student__History__index" */'@/pages/student/History/index.tsx')),
'6': React.lazy(() => import('./EmptyRoute')),
'7': React.lazy(() => import(/* webpackChunkName: "p__admin__Dashboard__index" */'@/pages/admin/Dashboard/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__admin__Equipments__index" */'@/pages/admin/Equipments/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__admin__Requests__index" */'@/pages/admin/Requests/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'E:/RIPT1307-02-2026-Nhom9-KTHP/frontend/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
